# Generated by Django 3.2.8 on 2021-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='EmailField',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
