# Generated by Django 3.2.8 on 2021-10-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_emailfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='EmailField',
            new_name='email',
        ),
    ]
